In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr=np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
 #2d array

In [19]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[0][0]

5

In [22]:
arr_2d[1][1]

25

In [23]:
arr_2d[2,2]

45

In [26]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#conditional selection

In [30]:
arrC=np.arange(1,11)

In [32]:
bool_arr=arrC>5

In [33]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
arrC

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arrC[bool_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
arrC[arrC<5]

array([1, 2, 3, 4])

In [39]:
arr_2dd= np.arange(50).reshape(5,10)

In [40]:
arr_2dd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2dd[1:3,:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])